#SPDX-License-Identifier: MIT-0
---
# vars file for common
service_user: engeneer
service_user_pss: $ANSIBLE_VAULT;1.1;AES256
          61656162623461383339336461306361643432306663663632383965343736353239653930316534
          3333626333313965346435313430653832393231613866620a653062343233643735356234373061
          64663335336331346364346636336337366336326338613136363864653265616537313839396462
          6264393230363630620a636632363664373239356262313232343762303062363339623833323161
          6532
#1234
service_dir: services
